### ISSUE TITLE
[OVERVIEW]:  launcher icons (keep ticket open!)

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm-neon#123]
Blacklisted apps:
- Cuttlefish (cuttlefish)
- External Drives (ciborium)
- Klipper (org.kde.klipper)
- Plasma Theme (org.kde.plasma.themeexplorer)
- Sync Monitor (syncmonitorhelper)

Currently active:

Phone, Browser, Calculator (click), Camera, 
Camera (click), Clock (?click?), Contacts, Gallery (click),
Koko, Konsole, Media Player (?popup?), Messaging,
Music (click), Phone, Phonebook, Settings, 
System Settings, Weather (click)

Suggest to Blacklist:
- Clocks (doesnt run)

**Comment by notmart** [comment]
the blacklist file is at
https://github.com/plasma-mobile/plasma-phone-settings/blob/master/etc/xdg/applications-blacklistrc

**Comment by notmart** [comment]
the package of plasma-phone-settings should be updated

**Comment by star-buck** [comment]
119:
Phone, Browser, Calculator, Camera, 
Camera, Clock, Contacts, Cuttlefish, 
External Drives, Gallery, Klipper, Koko, 
Konsole, Media Player, Messaging, Music Player,
Phone, Phonebook, Plasma Theme, Settings, 
Sync Monitor, System Settings, Weather

**Comment by jriddell** [comment]
doesn't seem to be in the image today, needs mobile ci to reappear to update plasma-phone-settings

**Comment by star-buck** [comment]
triggered rebuild of plasma-phone-settings

**Comment by jriddell** [comment]
building in mobile ci
