### ISSUE TITLE
[apps]: ship videoplayer

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm-neon#138]
llsvplayer packages deb armhf:
https://app.box.com/s/uyy8vrg87jxh8r04jjfqgpq7m0g60c8d
https://app.box.com/s/o71qozqaxblq8ikm76c6i88k35klc7q0

@jriddell : 
please include packages in new IMG

**Comment by jriddell** [comment]
jolla app
https://github.com/llelectronics/videoPlayer
needs libsailfishapp
https://github.com/sailfish-sdk/libsailfishapp
needs mlite5
https://github.com/nemomobile/mlite
and maybe more dependencies

**Comment by jriddell** [comment]
the .debs install fine but I can't get it to do anything

phablet@ubuntu-phablet:~$ vplayer  --help
Created Inout context: QComposeInputContext(0x16e8010)

it then quits

**Comment by star-buck** [comment]
@llelectronics :
Can you help with how to make your packages work?

**Comment by llelectronics** [comment]
@jriddell please see the https://github.com/llelectronics/videoPlayer/tree/plasma (Plasma Tree here for the source code)

As for the binary. 
./vplayer --phone should start the ui (when on desktop. On the phone the PLASMA_PLATFORM variable should be set so it should run without a problem)

**Comment by star-buck** [comment]
@jriddell l:
is the videoplayer shipped?

**Comment by star-buck** [comment]
@apachelogger :
Lets build packages of videoplayer in Mobile CI:
https://github.com/llelectronics/videoPlayer/tree/plasma

**Comment by star-buck** [comment]
@apachelogger :
Please build videoplayer from here:
https://github.com/plasma-apps/videoPlayer/tree/plasma

so package can be found in Mobile CI repo here:
http://mobile.kci.pangea.pub/pool/main/

**Comment by llelectronics** [comment]
I already added https://github.com/plasma-phone-packaging/videoPlayer-packaging 
So it just needs to be added to jenkins I guess :)

**Comment by star-buck** [comment]
@bhush9 : please try to build and ship this so we have a video player to test things on

**Comment by bhush9** [comment]
I've shipped it in IMG28 but doesn't start.

**Comment by llelectronics** [comment]
Any error message in the terminal?

**Comment by bhush9** [comment]
I've fixed it at packaging level to pass --phone to command line... it somehow fails to start even if PLASMA_PLATFORM=phone is set.

**Comment by bhush9** [comment]
In next image it will be working.

**Comment by star-buck** [comment]
i still dont see it shipped, please ship again.
