### ISSUE TITLE
[packaging] kconfig cmake files

### ISSUE THREAD

**Issue by aleixpol** [blue-systems/pm-neon#177]
Hi,
The package `libkf5config-bin-dev` should include the files:

```
/usr/lib/arm-linux-gnueabihf/cmake/KF5Config/KF5ConfigCompilerTargets.cmake
/usr/lib/arm-linux-gnueabihf/cmake/KF5Config/KF5ConfigCompilerTargets-debian.cmake
```

This is because we need to be able to have `libkf5config-bin-dev:amd64` installed together with `libkf5config-dev:armhf`.

**Comment by jriddell** [comment]
<sitter> not sure that makes sense
<sitter> libkf5config-dev:armhf would contain /usr/lib/arm-linux-gnueabihf/cmake/KF5Config
<sitter> libkf5config-bin-dev:amd64 would contain /usr/lib/amd64-linux-gnu/cmake/KF5Config
<sitter> an rdep would find former and former would somehow have to get latter (which literally makes no sense as then it might as well not find latter and simply find the binaries :P)
<sitter> also libkf5config-dev:amd64 and libkf5config-bin-dev:amd64 would conflict then
<sitter> I feel like aleix and I discussed this at some point and devised a cmake level solution

**Comment by bhush9** [comment]
I am not sure what is to be done here? or anything et all?

**Comment by star-buck** [comment]
@aleixpol : this be closed?
