### ISSUE TITLE
["About" kcm]: add neon-info

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm-neon#195]
so people see info about Distro name, Qt, Plasma versioning

**Comment by jriddell** [comment]
also needs a neon-settings package added

**Comment by jriddell** [comment]
about kcm is part of kinfocenter

**Comment by star-buck** [comment]
right, since its kci mobile, would refering to it as "neon"(-mobile) too, like kci desktop ISOs are labelled neon-files:
http://files.kde.org/snapshots/neon5-latest.iso.mirrorlist

**Comment by star-buck** [comment]
img13: still shows "Kubuntu" + logo in kinfocenter

**Comment by star-buck** [comment]
@bhush9 :
would be great if you look how to get it re-named and a more neutral logo (like "plasma" dots) shown, so once we also offer other builds from e.g. suse or debian, we know how to do this.

**Comment by jriddell** [comment]
neon-settings has the required files for this

> cat /etc/xdg/kcm-about-distrorc
> [General]
> LogoPath=/usr/share/pixmaps/neon.png
> Version=Developer Edition
> Variant=Unstable Branches

I guess it needs the equivalent added to mobile's settings package

**Comment by star-buck** [comment]
@bhush9 : kinfocenter now missing on current img?

**Comment by star-buck** [comment]
closing here, just needs kinfocenter installed again then works fine
