### ISSUE TITLE
[kmhajongg]: does start from konsole, but not from launcher

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm-neon#213]

**Comment by bhush9** [comment]
from konsole seems to start but being X application it doesn't get input it seems.. (CC: issue #217 )

**Comment by star-buck** [comment]
The input is not the problem here, lets make it start correctly as a
launcher first.

**Comment by star-buck** [comment]
saw this ticket is double, kmahjongg now works properly when started from console, but still fails to satrt via its own launcher.

**Comment by bhush9** [comment]
I just figured this is bug in kmahjongg itself probably.. 

kmahjongg: '<caption>' missing.
kmahjongg: Use --help to get a list of available command line options.

**Comment by bhush9** [comment]
Right... so kmahjongg we pull is from ubuntu, and it is kde4 version, we can build on mobile CI if required..

**Comment by bhush9** [comment]
http://commits.kde.org/plasma-phone-components/8d31e6b819e147878df01f2f261d8f58108d0754

Fixes this. Mainly this was our launcher removing %c part from the command line. so actual command line,

```kmahjongg -caption %c```

would become,

```kmahjongg -caption```

Which resulted in error provided above, there was implementation to launch application with KRun, but wasn't used actually..

**Comment by bhush9** [comment]
I will target this for next week's image.

**Comment by bhush9** [comment]
works in last image..

**Comment by star-buck** [comment]
needs shipping again, opened another ticket for that
