### ISSUE TITLE
[package request] Make build-dep for kaccounts* work

### ISSUE THREAD

**Issue by mck182** [blue-systems/pm-neon#248]
sudo apt-get build-dep kaccounts-mobile would be very handy to get quickly all the stuff that is needed to work on that. Same for kaccounts-integration.

**Comment by bhush9** [comment]
Hmm? whats preventing that? I don't understand.

**Comment by mck182** [comment]
No clue.

$ sudo apt-get build-dep kaccounts-mobile

E: Unable to find a source package for kaccounts-mobile

(same with kaccounts-integration)

**Comment by bhush9** [comment]
Ah, right, deb-src for mobile CI is not enabled in mobile IMG. I will make sure this gets corrected in next image.

**Comment by bhush9** [comment]
Mean while please add,

```
deb-src http://mobile.kci.pangea.pub vivid main
```

to your sources.lst

**Comment by bhush9** [comment]
fixed in : http://commits.kde.org/mobster/855e0713b5fc281cb4be4add86f1ff5b217e130a

**Comment by mck182** [comment]
Awesome, thanks!

**Comment by bhush9** [comment]
(also, I should replace mobile.kci with mobile.neon but that will require updating in all other places I believe)

**Comment by mck182** [comment]
> Mean while please add,

It's there already, just commented out btw.

**Comment by bhush9** [comment]
The way I added it didn't work out.. will need to find another way...

**Comment by bhush9** [comment]
now that we are using live-build to create images, this is fixed, next week's image should have this fixed..

**Comment by bhush9** [comment]
Fixed in image published today..
