### ISSUE TITLE
[apps]: music player

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm-neon#76]

**Comment by bhush9** [comment]
img17 have ubuntu's music-app installed.

**Comment by bhush9** [comment]
Ubuntu's music app will not work in recent images due to incompatibility with libhybris. So one will need to find something else as solution of music player app

**Comment by star-buck** [comment]
any suggestions what to ship for now?

**Comment by bhush9** [comment]
We can try elisa / babe music player..

**Comment by luebking** [comment]
mpd. It has like no footprint, can maintain a local database, proxy a remote one and there's a truckload of clients.

**Comment by star-buck** [comment]
for the purpose of demonstrating "a full linux stack + plasma desktop in your pocket" awesomeness
- install "audacious"
- set default to "Winamp Style" and "double size"

**Comment by bhush9** [comment]
I might be blind, but i can't find option to set "double size"?

**Comment by star-buck** [comment]
Its in one of the dropdown menus, not the settings.

On Dec 14, 2017 07:54, "Bhushan Shah" <notifications@github.com> wrote:

I might be blind, but i can't find option to set "double size"?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/blue-systems/pm-neon/issues/76#issuecomment-351751534>,
or mute the thread

**Comment by llelectronics** [comment]
If you right click on the player you can set it.

**Comment by bhush9** [comment]
> If you right click ...

And how do I do it on phone? :P

**Comment by star-buck** [comment]
Just see on the desktop and ship the config.

**Comment by bhush9** [comment]
Yeah, figured out config entry.. will build image in few minutes.

**Comment by bhush9** [comment]
Image `20171214-165756` includes audacious, however somehow the Winamp style is not default, will correct in next image.

**Comment by star-buck** [comment]
lets also set "default font sizes" for playlist and player from 9 to 24 pixels, and disbale bitmap font.
